In [1]:
print("Hello")

Hello


In [2]:
import numpy as np
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("nomic-ai/nomic-embed-text-v1.5", trust_remote_code=True)

text = "A simple, free, and efficient way to vectorize text."

vector = model.encode(f"search_query: {text}")

print(f"Object Type: {type(vector)}")  # Output: <class 'numpy.ndarray'>
print(f"Vector Dimensions: {vector.shape}")  # Output: (768,)
print(f"Sample values: {vector[:5]}")

<All keys matched successfully>
[transformers] Detected the usage of `get_extended_attention_mask`: This function is deprecated and will be removed in v5.12.0. Please use the new API in `transformers.masking_utils`


Object Type: <class 'numpy.ndarray'>
Vector Dimensions: (768,)
Sample values: [ 1.3932841   1.0728705  -3.9158149  -0.9002627   0.01798691]


In [6]:
from functions import text_vectorize_score

result = text_vectorize_score("I have a cute little doll", "I wish my dog was gray.")
print(result["cosine_similarity"])
print(result["BERTScore_F1"].item())
print(result["BERTScore_P"].item())
print(result["BERTScore_R"].item())

<All keys matched successfully>
Loading weights: 100%|██████████| 100/100 [00:00<?, ?it/s]

0.48466048
0.7399899959564209
0.7310744524002075
0.7491257190704346


In [9]:
from functions import code_vectorize_score

code_result = code_vectorize_score("factorial = lambda n: 1 if n <= 1 else n * factorial(n - 1)", "def is_palindrome(s): return s == s[::-1]")
print(code_result["cosine_similarity"])
print(code_result["BERTScore_F1"])
print(code_result["BERTScore_P"])
print(code_result["BERTScore_R"])

Loading weights: 100%|██████████| 199/199 [00:00<?, ?it/s]

tensor([0.2558])
tensor([0.6242])
tensor([0.6398])
tensor([0.6093])


In [11]:
from functions import data_completion_score

data_result = data_completion_score(185000, 233200)
print(data_result)

2323240000
